-- Нулират се броячите
delete from SID
GO

-- 0. ММС таблиците

delete from mms_vpisvane_doc
go
delete from mms_vpisvane
go
delete from mms_dop_pol
go
delete from mms_adm_etal_dop
go
delete from mms_vid_sport
go
delete from mms_chlenstvo
go
delete from mms_coaches_diploms
go
delete from mms_coaches
go
delete from mms_sport_formirovanie
go
delete from mms_sport_obed_mf
go
delete from mms_sport_obedinenie
go
delete from mms_sport_obekt_lice
go
delete from mms_sport_obekt
go


DROP SEQUENCE seq_mms_adm_etal_dop
go
DROP SEQUENCE seq_mms_chlenstvo
go
DROP SEQUENCE seq_mms_coaches
go
DROP SEQUENCE seq_mms_coaches_diploms
go
DROP SEQUENCE seq_mms_dop_pol
go
DROP SEQUENCE seq_mms_sport_formirovanie
go
DROP SEQUENCE seq_mms_sport_obed_mf
go
DROP SEQUENCE seq_mms_sport_obedninenie
go
DROP SEQUENCE seq_mms_sport_obekt
go
DROP SEQUENCE seq_mms_sport_obekt_lice
go
DROP SEQUENCE seq_mms_vid_sport
go
DROP SEQUENCE seq_mms_vpisvane
go
DROP SEQUENCE seq_mms_vpisvane_doc
go


CREATE SEQUENCE seq_mms_adm_etal_dop INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
go
CREATE SEQUENCE seq_mms_chlenstvo INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
go
CREATE SEQUENCE seq_mms_coaches INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
go
CREATE SEQUENCE seq_mms_coaches_diploms INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
go
CREATE SEQUENCE seq_mms_dop_pol INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
go
CREATE SEQUENCE seq_mms_sport_formirovanie INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
go
CREATE SEQUENCE seq_mms_sport_obed_mf INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
go
CREATE SEQUENCE seq_mms_sport_obedninenie INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
go
CREATE SEQUENCE seq_mms_sport_obekt INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
go
CREATE SEQUENCE seq_mms_sport_obekt_lice INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
go
CREATE SEQUENCE seq_mms_vid_sport INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
go
CREATE SEQUENCE seq_mms_vpisvane INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
go
CREATE SEQUENCE seq_mms_vpisvane_doc INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
go


-- 1. СИСТЕМНИ КЛАСИФИКАЦИИ И НАСТРОЙКИ

-- 1.2. Сетвам кои класификации може да се редактират и кои не
-- Не може да редактират:
--update SYSTEM_CLASSIF_OPIS set USER_EDITABLE = 'f' where ID not in (22,25,104,105,106,110,115,116,120,124,126,130,133,134,135,136,138,141,145,157,160,164,166,171,172,174,176)
--GO
-- Може да редактират:
--update SYSTEM_CLASSIF_OPIS set USER_EDITABLE = 't' where ID in     (22,25,104,105,106,110,115,116,120,124,126,130,133,134,135,136,138,141,145,157,160,164,166,171,172,174,176)
--GO

-- 1.3. Изтривам съдържанието на класификации, които трябва да се дефинират при клиента
delete from SYSCLASSIF_MULTILANG where TEKST_KEY in (select TEKST_KEY from SYSTEM_CLASSIF where CODE_CLASSIF in (126,166,171,172,174,176))
GO
delete from SYSTEM_CLASSIF where CODE_CLASSIF in (126,166,171,172,174,176)
GO

-- 1.4. Зачистване на история и нулиране на датите от-до
delete from SYSTEM_CLASSIF where DATE_DO is not null
GO
update SYSTEM_CLASSIF set DATE_OT = TO_DATE('01.01.1901','DD.MM.YYYY'), USER_REG = -1, DATE_REG = TO_DATE('01.01.1901','DD.MM.YYYY'), USER_LAST_MOD = null, DATE_LAST_MOD = null
GO
update SYSTEM_CLASSIF_OPIS set USER_REG = -1, DATE_REG = TO_DATE('01.01.1901','DD.MM.YYYY'), USER_LAST_MOD = null, DATE_LAST_MOD = null
GO
update SYSLOGIC_LIST set USER_REG = -1, DATE_REG = TO_DATE('01.01.1901','DD.MM.YYYY'), USER_LAST_MOD = null, DATE_LAST_MOD = null
GO
update SYSLOGIC_LIST_OPIS set USER_REG = -1, DATE_REG = TO_DATE('01.01.1901','DD.MM.YYYY'), USER_LAST_MOD = null, DATE_LAST_MOD = null
GO

-- 2. РЕФЕРЕНТИ+
-- Изтрива се всичко
delete from ADM_REF_ADDRS 
GO
delete from ADM_REFERENTS
GO
delete from USER_NOTIFICATIONS
GO
delete from LOCK_OBJECTS
GO
delete from SYSTEM_JOURNAL
GO
-- Пресъздават се и SEQUENCE-ите
DROP SEQUENCE SEQ_ADM_REFERENTS
GO
DROP SEQUENCE SEQ_ADM_REFERENTS_CODE
GO
DROP SEQUENCE SEQ_ADM_REF_ADDRS
GO
DROP SEQUENCE SEQ_USER_MESSAGES
GO
DROP SEQUENCE SEQ_SYSTEM_JOURNAL
GO
CREATE SEQUENCE SEQ_ADM_REFERENTS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_ADM_REFERENTS_CODE INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_ADM_REF_ADDRS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_USER_MESSAGES INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_SYSTEM_JOURNAL INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO


-- 3. РЕГИСТРАТУРИ-СВЪРЗАНИ ОБЕКТИ
-- Изтрива се всичко
delete from REGISTRATURA_REGISTER
GO
delete from ADM_REF_DELEGATIONS
GO
delete from REGISTRATURA_REFERENTS
GO
delete from REGISTRATURA_GROUPS
GO
delete from REGISTRATURA_MAILBOXES_VARS
GO
delete from REGISTRATURA_MAILBOXES
GO
--delete from DOC_VID_SETTINGS
--GO
--delete from REGISTRATURA_SETTINGS where registratura_id <> 1
--GO
delete from DOC_SHEMA
GO
delete from DOC_WS_OPTIONS
GO
-- Пресъздават се и SEQUENCE-ите
DROP SEQUENCE SEQ_ADM_REF_DELEGATIONS
GO
DROP SEQUENCE SEQ_REGISTRATURA_REFERENTS
GO
DROP SEQUENCE SEQ_REGISTRATURA_GROUPS
GO
DROP SEQUENCE SEQ_MAILBOXES_VARS
GO
DROP SEQUENCE SEQ_REGISTRATURA_MAILBOXES
GO
--DROP SEQUENCE SEQ_DOC_VID_SETTINGS
--GO
--DROP SEQUENCE SEQ_REGISTRATURA_SETTINGS
--GO
DROP SEQUENCE SEQ_DOC_SHEMA
GO
DROP SEQUENCE SEQ_DOC_WS_OPTIONS
GO
CREATE SEQUENCE SEQ_ADM_REF_DELEGATIONS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_REGISTRATURA_REFERENTS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_REGISTRATURA_GROUPS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_MAILBOXES_VARS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_REGISTRATURA_MAILBOXES INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
--CREATE SEQUENCE SEQ_DOC_VID_SETTINGS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
--GO
--CREATE SEQUENCE SEQ_REGISTRATURA_SETTINGS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
--GO
CREATE SEQUENCE SEQ_DOC_SHEMA INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_DOC_WS_OPTIONS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO


-- 14. ПРОЦЕДУРИ
delete from praznici
go
delete from proc_exe_task
go
delete from proc_exe_etap
go
delete from proc_exe
go
DROP SEQUENCE seq_praznici
go
DROP SEQUENCE seq_proc_exe_task
go
DROP SEQUENCE seq_proc_exe_etap
go
DROP SEQUENCE seq_proc_exe
go
create sequence seq_praznici increment by 1 minvalue 0 maxvalue 2147483647 start with 1 cache 1 no cycle
go
create sequence seq_proc_exe_task increment by 1 minvalue 0 maxvalue 2147483647 start with 1 cache 1 no cycle
go
create sequence seq_proc_exe_etap increment by 1 minvalue 0 maxvalue 2147483647 start with 1 cache 1 no cycle
go
create sequence seq_proc_exe increment by 1 minvalue 0 maxvalue 2147483647 start with 1 cache 1 no cycle
go

-- 4. ЗАДАЧИ
-- Изтрива се всичко
delete from TASK_SCHEDULE
GO
delete from TASK_STATES
GO
delete from TASK_REFERENTS
GO
delete from TASK
GO

-- Пресъздават се и SEQUENCE-ите
DROP SEQUENCE SEQ_TASK_SCHEDULE
GO
DROP SEQUENCE SEQ_TASK_STATES
GO
DROP SEQUENCE SEQ_TASK_REFERENTS
GO
DROP SEQUENCE SEQ_TASK
GO
CREATE SEQUENCE SEQ_TASK_SCHEDULE INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_TASK_STATES INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_TASK_REFERENTS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_TASK INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO


-- 5. ПРЕПИСКИ
-- Изтрива се всичко
delete from DELO_ACCESS
GO
delete from DELO_ACCESS_ALL
GO
delete from DELO_DELO
GO
delete from DELO_DOC
GO
delete from DELO_DVIJ
GO
delete from DELO_ARCHIVE
GO
delete from DELO_STORAGE
GO
delete from DELO
GO
-- Пресъздават се и SEQUENCE-ите
DROP SEQUENCE SEQ_DELO_ACCESS
GO
DROP SEQUENCE SEQ_DELO_DELO
GO
DROP SEQUENCE SEQ_DELO_DOC
GO
DROP SEQUENCE SEQ_DELO_DVIJ
GO
DROP SEQUENCE SEQ_DELO_ARCHIVE
GO
DROP SEQUENCE SEQ_DELO_STORAGE
GO
DROP SEQUENCE SEQ_DELO
GO
CREATE SEQUENCE SEQ_DELO_ACCESS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_DELO_DELO INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_DELO_DOC INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_DELO_DVIJ INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_DELO_ARCHIVE INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_DELO_STORAGE INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_DELO INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO


-- 6. ДОКУМЕНТИ
-- Изтрива се всичко
delete from DOC_ACCESS
GO
delete from DOC_ACCESS_ALL
GO
delete from DOC_DOC
GO
delete from DOC_DVIJ
GO
delete from DOC_DESTRUCT
GO
delete from DOC_TOPIC
GO
delete from DOC_PRIL
GO
delete from DOC_REFERENTS
GO
delete from DOC_DOPDATA
GO
delete from DOC_MEMBERS
GO
delete from DOC
GO
-- Пресъздават се и SEQUENCE-ите
DROP SEQUENCE SEQ_DOC_ACCESS
GO
DROP SEQUENCE SEQ_DOC_DOC
GO
DROP SEQUENCE SEQ_DOC_DVIJ
GO
DROP SEQUENCE SEQ_DOC_DESTRUCT
GO
DROP SEQUENCE SEQ_DOC_PRIL
GO
DROP SEQUENCE SEQ_DOC_REFERENTS
GO
DROP SEQUENCE SEQ_DOC_DOPDATA
GO
DROP SEQUENCE SEQ_DOC_MEMBERS
GO
DROP SEQUENCE SEQ_DOC
GO
CREATE SEQUENCE SEQ_DOC_ACCESS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_DOC_DOC INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_DOC_DVIJ INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_DOC_DESTRUCT INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_DOC_PRIL INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_DOC_REFERENTS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_DOC_DOPDATA INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_DOC_MEMBERS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_DOC INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO


-- 7. РЕГИСТРАТУРИ
-- Изтрива се всичко
--delete from REGISTRI
--GO
--delete from REGISTRATURI where registratura_id <> 1
--GO
-- Пресъздават се и SEQUENCE-ите
--DROP SEQUENCE SEQ_REGISTRI
--GO
--DROP SEQUENCE SEQ_REGISTRATURI
--GO
--CREATE SEQUENCE SEQ_REGISTRI INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 5 CACHE 1 NO CYCLE
--GO
--CREATE SEQUENCE SEQ_REGISTRATURI INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
--GO

--INSERT INTO registri(register_id, registratura_id, register, register_type, valid, common, doc_type, prefix, alg, beg_nomer, act_nomer, step, sort_nomer, user_reg, date_reg)
--  VALUES(1, 1, 'Индекс и стъпка за собствени док.', 1, 1, 2, 2, 'СД', 1, 1, 1, 1, NULL, -1, '2022-07-28')
--GO
--INSERT INTO registri(register_id, registratura_id, register, register_type, valid, common, doc_type, prefix, alg, beg_nomer, act_nomer, step, sort_nomer, user_reg, date_reg)
--  VALUES(2, 1, 'Заявления от Архимед', 2, 1, 2, 1, NULL, 3, 1, 1, 1, NULL, -1, '2022-07-28')
--GO
--INSERT INTO registri(register_id, registratura_id, register, register_type, valid, common, doc_type, prefix, alg, beg_nomer, act_nomer, step, sort_nomer, user_reg, date_reg)
--  VALUES(3, 1, 'Индекс и стъпка за работни док.', 1, 1, 2, 3, 'РД', 1, 1, 1, 1, NULL, -1, '2022-07-28')
--GO
--INSERT INTO registri(register_id, registratura_id, register, register_type, valid, common, doc_type, prefix, alg, beg_nomer, act_nomer, step, sort_nomer, user_reg, date_reg)
--  VALUES(4, 1, 'Заявления за вписване', 1, 1, 2, NULL, NULL, 3, 1, 1, 1, NULL, -1, '2022-07-28')
--GO


--INSERT INTO doc_vid_settings(id, registratura_id, doc_vid, register_id, create_delo, user_reg, date_reg, members_active)
--  VALUES(1, 1, 34, 2, 2, -1, '2022-07-22 15:35:26.962', 2)
--GO
--INSERT INTO doc_vid_settings(id, registratura_id, doc_vid, register_id, create_delo, user_reg, date_reg, members_active)
--  VALUES(2, 1, 38, 2, 2, -1, '2022-07-22 15:37:40.349', 2)
--GO
--INSERT INTO doc_vid_settings(id, registratura_id, doc_vid, register_id, create_delo, user_reg, date_reg, members_active)
--  VALUES(3, 1, 37, 2, 2, -1, '2022-07-28 09:58:58.582', 2)
--GO
--INSERT INTO doc_vid_settings(id, registratura_id, doc_vid, register_id, create_delo, user_reg, date_reg, members_active)
--  VALUES(4, 1, 41, 1, 2, -1, '2022-07-28 09:59:22.146', 2)
--GO
--INSERT INTO doc_vid_settings(id, registratura_id, doc_vid, register_id, create_delo, user_reg, date_reg, members_active)
--  VALUES(5, 1, 50, 1, 2, -1, '2022-07-18 12:50:11.649', 2)
--GO
--INSERT INTO doc_vid_settings(id, registratura_id, doc_vid, register_id, create_delo, user_reg, date_reg, members_active)
--  VALUES(6, 1, 36, 2, 2, -1, '2022-07-14 21:17:31.297', 2)
--GO
--INSERT INTO doc_vid_settings(id, registratura_id, doc_vid, register_id, create_delo, user_reg, date_reg, members_active)
--  VALUES(7, 1, 40, 2, 2, -1, '2022-07-15 13:06:00.541', 2)
--GO
--INSERT INTO doc_vid_settings(id, registratura_id, doc_vid, register_id, create_delo, user_reg, date_reg, members_active)
--  VALUES(8, 1, 48, 1, 2, -1, '2022-07-18 12:47:26.962', 2)
--GO
--INSERT INTO doc_vid_settings(id, registratura_id, doc_vid, register_id, create_delo, user_reg, date_reg, members_active)
--  VALUES(9, 1, 49, 1, 2, -1, '2022-07-18 12:48:55.483', 2)
--GO
--INSERT INTO doc_vid_settings(id, registratura_id, doc_vid, register_id, create_delo, user_reg, date_reg, members_active)
--  VALUES(11, 1, 45, 1, 2, -1, '2022-07-18 12:41:08.531', 2)
--GO
--INSERT INTO doc_vid_settings(id, registratura_id, doc_vid, register_id, create_delo, user_reg, date_reg, members_active)
--  VALUES(12, 1, 44, 1, 2, -1, '2022-07-18 12:40:18.628', 2)
--GO
--INSERT INTO doc_vid_settings(id, registratura_id, doc_vid, register_id, create_delo, user_reg, date_reg, members_active)
--  VALUES(13, 1, 42, 1, 2, -1, '2022-07-18 12:22:16.059', 2)
--GO
--INSERT INTO doc_vid_settings(id, registratura_id, doc_vid, register_id, create_delo, user_reg, date_reg, members_active)
--  VALUES(14, 1, 43, 1, 2, -1, '2022-07-18 12:36:23.967', 2)
--GO
--INSERT INTO doc_vid_settings(id, registratura_id, doc_vid, register_id, create_delo, user_reg, date_reg, members_active)
--  VALUES(15, 1, 46, 1, 2, -1, '2022-07-18 12:43:05.549', 2)
--GO
--INSERT INTO doc_vid_settings(id, registratura_id, doc_vid, register_id, create_delo, user_reg, date_reg, members_active)
--  VALUES(16, 1, 47, 1, 2, -1, '2022-07-18 12:45:47.879', 2)
--GO


--DROP SEQUENCE SEQ_DOC_VID_SETTINGS
--GO
--CREATE SEQUENCE SEQ_DOC_VID_SETTINGS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 17 CACHE 1 NO CYCLE
--GO


-- 8. ФАЙЛОВЕ
-- Изтрива се всичко
delete from FILE_OBJECTS
GO
delete from FILES
GO
-- Пресъздават се и SEQUENCE-ите
DROP SEQUENCE SEQ_FILE_OBJECTS
GO
DROP SEQUENCE SEQ_FILES
GO
CREATE SEQUENCE SEQ_FILE_OBJECTS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_FILES INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO


-- 9. ПОТРЕБИТЕЛИ И ГРУПИ
-- Изтриват се всички потребители без -1(zxc).
-- Изтриват се и правата му, като накрая се зареждат няколко за да може да се логне и да си даде каквото му трябва
delete from ADM_USER_GROUP
GO
delete from ADM_GROUP_ROLES
GO
delete from ADM_GROUPS
GO
delete from ADM_USER_CERTS
GO
delete from ADM_USER_ROLES
GO
delete from ADM_USERS where USER_ID not in (-1,33,23,30,25,35,24)
GO
--Mery	Мариана Петкова	mpetkova@indexbg.bg
--daniv	Даниела Василева	d.vasileva@indexbg.bg
--maria	Мария Павлова	m.pavlova@indexbg.bg
--Tanya	Таня Иванова	t.ivanova@indexbg.bg

-- Пресъздават се и SEQUENCE-ите
DROP SEQUENCE SEQ_ADM_GROUP_ROLES
GO
DROP SEQUENCE SEQ_ADM_GROUPS
GO
DROP SEQUENCE SEQ_ADM_USER_CERTS
GO
DROP SEQUENCE SEQ_ADM_USER_ROLES
GO
DROP SEQUENCE SEQ_ADM_USERS
GO
CREATE SEQUENCE SEQ_ADM_GROUP_ROLES INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_ADM_GROUPS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_ADM_USER_CERTS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_ADM_USER_ROLES INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_ADM_USERS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 36 CACHE 1 NO CYCLE
GO
-- Зареждам за -1(zxc) права за достъп до менюта
insert into ADM_USER_ROLES(ROLE_ID, USER_ID, CODE_CLASSIF, CODE_ROLE) values(-10,-1,7,4)
GO
insert into ADM_USER_ROLES(ROLE_ID, USER_ID, CODE_CLASSIF, CODE_ROLE) values(-9,-1,7,1)
GO
insert into ADM_USER_ROLES(ROLE_ID, USER_ID, CODE_CLASSIF, CODE_ROLE) values(-8,-1,7,2)
GO
insert into ADM_USER_ROLES(ROLE_ID, USER_ID, CODE_CLASSIF, CODE_ROLE) values(-7,-1,7,3)
GO
insert into ADM_USER_ROLES(ROLE_ID, USER_ID, CODE_CLASSIF, CODE_ROLE) values(-6,-1,7,7)
GO
insert into ADM_USER_ROLES(ROLE_ID, USER_ID, CODE_CLASSIF, CODE_ROLE) values(-5,-1,7,31)
GO
insert into ADM_USER_ROLES(ROLE_ID, USER_ID, CODE_CLASSIF, CODE_ROLE) values(-4,-1,7,32)
GO
insert into ADM_USER_ROLES(ROLE_ID, USER_ID, CODE_CLASSIF, CODE_ROLE) values(-3,-1,7,38)
GO
insert into ADM_USER_ROLES(ROLE_ID, USER_ID, CODE_CLASSIF, CODE_ROLE) values(-2,-1,7,40)
GO
insert into ADM_USER_ROLES(ROLE_ID, USER_ID, CODE_CLASSIF, CODE_ROLE) values(-1,-1,7,91)
GO


-- 10. ИНФОРМАЦИОННИ МОДЕЛИ И СПРАВКИ
-- Изтрива се всичко
delete from UNIVERSAL_REPORT
GO
--delete from SPR_STAT_ELEMENTS
--GO
--delete from SPR_STAT_TABLES
--GO
--delete from MODEL_ATTRIBUTES
--GO
--delete from MODEL_OBJECTS
--GO
--delete from MODEL_PERSISTENCE
--GO
--delete from MODEL_TABLE_JOINS
--GO
--delete from MODEL_TABLES
--GO
--delete from MODEL_AIS
--GO
--delete from MODEL_MULTILANG
--GO
-- Пресъздават се и SEQUENCE-ите
DROP SEQUENCE SEQ_U_REPORT
GO
--DROP SEQUENCE SEQ_SPR_STAT_ELEMENTS
--GO
--DROP SEQUENCE SEQ_SPR_STAT_TABLES
--GO
--DROP SEQUENCE SEQ_MODEL_ATTRIBUTES
--GO
--DROP SEQUENCE SEQ_MODEL_OBJECTS
--GO
--DROP SEQUENCE SEQ_MODEL_PERSISTENCE
--GO
--DROP SEQUENCE SEQ_MODEL_TABLE_JOINS
--GO
--DROP SEQUENCE SEQ_MODEL_TABLES
--GO
--DROP SEQUENCE SEQ_MODEL_AIS
--GO
--DROP SEQUENCE SEQ_MODEL_MULTILANG
--GO
--DROP SEQUENCE SEQ_MODEL_ELEMENT_CODE
--GO
CREATE SEQUENCE SEQ_U_REPORT INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
GO
--CREATE SEQUENCE SEQ_SPR_STAT_ELEMENTS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
--GO
--CREATE SEQUENCE SEQ_SPR_STAT_TABLES INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
--GO
--CREATE SEQUENCE SEQ_MODEL_ATTRIBUTES INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
--GO
--CREATE SEQUENCE SEQ_MODEL_OBJECTS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
--GO
--CREATE SEQUENCE SEQ_MODEL_PERSISTENCE INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
--GO
--CREATE SEQUENCE SEQ_MODEL_TABLE_JOINS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
--GO
--CREATE SEQUENCE SEQ_MODEL_TABLES INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
--GO
--CREATE SEQUENCE SEQ_MODEL_AIS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
--GO
--CREATE SEQUENCE SEQ_MODEL_MULTILANG INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
--GO
--CREATE SEQUENCE SEQ_MODEL_ELEMENT_CODE INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE
--GO


-- 11. ЕГОВ ТАБЛИЦИ
-- !!! Ако трябва да се трият се пуска това:
--delete from EDELIVERY_ORGANISATIONS
--GO
--delete from EGOV_ORGANISATIONS
--GO
--delete from EGOV_SERVICES
--GO
--delete from EGOV_NOMENKLATURI
--GO
--delete from EGOV_MESSAGES_CORESP
--GO
--delete from EGOV_MESSAGES_FILES
--GO
--delete from EGOV_MESSAGES_OTHER
--GO
--delete from EGOV_MESSAGES
--GO
--update EGOV_SID set NEXT_VAL = 1
--GO
---- !!! Ако са изтрити трябва да се пресъздават и SEQUENCE-и
--DROP SEQUENCE SEQ_EGOV_MESSAGES_CORESP
--GO
--DROP SEQUENCE SEQ_EGOV_MESSAGES_FILES
--GO
--DROP SEQUENCE SEQ_EGOV_MESSAGES
--GO
--CREATE SEQUENCE SEQ_EGOV_MESSAGES_CORESP INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1000000001 CACHE 1 NO CYCLE
--GO
--CREATE SEQUENCE SEQ_EGOV_MESSAGES_FILES INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1000000001 CACHE 1 NO CYCLE
--GO
--CREATE SEQUENCE SEQ_EGOV_MESSAGES INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 1000000001 CACHE 1 NO CYCLE
--GO


-- 12. КВАРЦ ТАБЛИЦИ
-- !!! Ако трябва да се трият се пуска това:
delete from JOB_HISTORY
GO
delete from QRTZ_BLOB_TRIGGERS
GO
delete from QRTZ_CALENDARS
GO
delete from QRTZ_CRON_TRIGGERS
GO
delete from QRTZ_FIRED_TRIGGERS
GO
delete from QRTZ_LOCKS
GO
delete from QRTZ_PAUSED_TRIGGER_GRPS
GO
delete from QRTZ_SCHEDULER_STATE
GO
delete from QRTZ_SIMPLE_TRIGGERS
GO
delete from QRTZ_SIMPROP_TRIGGERS
GO
delete from QRTZ_TRIGGERS
GO
delete from QRTZ_JOB_DETAILS
GO


-- 13. ОРГАНИЦИРАНИ СЪБИТИЯ
delete from event_referents
go
delete from event_resources
go
delete from events
go
DROP SEQUENCE seq_events
GO
create sequence seq_events increment by 1 minvalue 0 maxvalue 2147483647 start with 1 cache 1 no cycle
go


-- 15. ДРУГИ ТАБЛИЦИ
-- за всякакви други таблици като тестови трябва да се изтрият или дроп-нат
--drop table PLAN_TABLE
--go
--drop table MIG_CODE_TABLE -- трябва за миграция, но за празна база няма нужда
--GO
--drop table KG_DELME -- ТЕСТОВИ
--GO

-- 16. SEQ НА КОИТО ТРЯБВА ДА СЕ СМЕНИ NOCACHE, ЗАЩОТО ГОРЕ НЕ СЕ ПРЕСЪЗДАВАТ
alter sequence seq_mail_patterns cache 1
GO
alter sequence seq_mail_patterns_variables cache 1
GO
alter sequence seq_sysclassif_multilang cache 1
GO
alter sequence seq_syslogic_list cache 1
GO
alter sequence seq_syslogic_list_opis cache 1
GO
alter sequence seq_system_classif cache 1
GO
alter sequence seq_system_classif_opis cache 1
GO
alter sequence seq_system_options cache 1
GO


-- 17. ЗАРЕЖДАНЕ НА НАЧАЛНИ ДАННИ
-- Регистратура
--INSERT INTO REGISTRATURI(REGISTRATURA_ID, REGISTRATURA, VALID, ORG_NAME, USER_REG, DATE_REG)
--VALUES(1, 'Име на Регистратура', 1, 'Име на Организация', -1, TO_DATE('1901-01-01','YYYY-MM-DD'))
--GO
DROP SEQUENCE SEQ_REGISTRATURI
GO
CREATE SEQUENCE SEQ_REGISTRATURI INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 2 CACHE 1 NO CYCLE
GO

-- Корена на административната структура
INSERT INTO ADM_REFERENTS(REF_ID, CODE, CODE_PREV, CODE_PARENT, CODE_CLASSIF, REF_TYPE, REF_REGISTRATURA, REF_NAME, REF_LATIN, REF_GRJ, REF_INFO, DATE_OT, DATE_DO, TAX_OFFICE_NO, CONTACT_PHONE, CONTACT_EMAIL, MAX_UPLOAD_SIZE, EMPL_POSITION, EMPL_CONTRACT, NFL_EIK, FZL_EGN, FZL_LNC, FZL_LN_ES, FZL_BIRTH_DATE, USER_REG, DATE_REG, USER_LAST_MOD, DATE_LAST_MOD, LEVEL_NUMBER, MIG_LOGIN_NAME)
VALUES(1, 1, 0, 0, 24, 1, 1, 'Министерство на младежта и спорта', NULL, NULL, NULL, TO_DATE('1901-01-01','YYYY-MM-DD'), TO_DATE('2999-12-31','YYYY-MM-DD')
    , NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -1, TO_DATE('1901-01-01','YYYY-MM-DD'), NULL, NULL, NULL, NULL)
GO
INSERT INTO ADM_REFERENTS(REF_ID, CODE, CODE_PREV, CODE_PARENT, CODE_CLASSIF, REF_TYPE, REF_REGISTRATURA, REF_NAME, REF_LATIN, REF_GRJ, REF_INFO, DATE_OT, DATE_DO, TAX_OFFICE_NO, CONTACT_PHONE, CONTACT_EMAIL, MAX_UPLOAD_SIZE, EMPL_POSITION, EMPL_CONTRACT, NFL_EIK, FZL_EGN, FZL_LNC, FZL_LN_ES, FZL_BIRTH_DATE, USER_REG, DATE_REG, USER_LAST_MOD, DATE_LAST_MOD, LEVEL_NUMBER, MIG_LOGIN_NAME)
VALUES(2, 2, 0, 1, 24, 1, 1, 'Тестови служители', NULL, NULL, NULL, TO_DATE('1901-01-01','YYYY-MM-DD'), TO_DATE('2999-12-31','YYYY-MM-DD')
    , NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -1, TO_DATE('1901-01-01','YYYY-MM-DD'), NULL, NULL, NULL, NULL)
GO
-- слагам и ZXC като системен служител
INSERT INTO ADM_REFERENTS(REF_ID, CODE, CODE_PREV, CODE_PARENT, CODE_CLASSIF, REF_TYPE, REF_REGISTRATURA, REF_NAME, REF_LATIN, REF_GRJ, REF_INFO, DATE_OT, DATE_DO, TAX_OFFICE_NO, CONTACT_PHONE, CONTACT_EMAIL, MAX_UPLOAD_SIZE, EMPL_POSITION, EMPL_CONTRACT, NFL_EIK, FZL_EGN, FZL_LNC, FZL_LN_ES, FZL_BIRTH_DATE, USER_REG, DATE_REG, USER_LAST_MOD, DATE_LAST_MOD, LEVEL_NUMBER, MIG_LOGIN_NAME)
VALUES(-1, -1, 0, 2, 24, 2, NULL, 'Системен служител', NULL, NULL, NULL, TO_DATE('1901-01-01','YYYY-MM-DD'), TO_DATE('2999-12-31','YYYY-MM-DD')
    , NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -1, TO_DATE('1901-01-01','YYYY-MM-DD'), NULL, NULL, NULL, NULL)
GO
INSERT INTO ADM_REFERENTS(REF_ID, CODE, CODE_PREV, CODE_PARENT, CODE_CLASSIF, REF_TYPE, REF_REGISTRATURA, REF_NAME, REF_LATIN, REF_GRJ, REF_INFO, DATE_OT, DATE_DO, TAX_OFFICE_NO, CONTACT_PHONE, CONTACT_EMAIL, MAX_UPLOAD_SIZE, EMPL_POSITION, EMPL_CONTRACT, NFL_EIK, FZL_EGN, FZL_LNC, FZL_LN_ES, FZL_BIRTH_DATE, USER_REG, DATE_REG, USER_LAST_MOD, DATE_LAST_MOD, LEVEL_NUMBER, MIG_LOGIN_NAME)
VALUES(23, 23, -1, 2, 24, 2, NULL, 'Георги Белев', NULL, NULL, NULL, TO_DATE('1901-01-01','YYYY-MM-DD'), TO_DATE('2999-12-31','YYYY-MM-DD')
    , NULL, NULL, 'gbelev@indexbg.bg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -1, TO_DATE('1901-01-01','YYYY-MM-DD'), NULL, NULL, NULL, NULL)
GO
INSERT INTO ADM_REFERENTS(REF_ID, CODE, CODE_PREV, CODE_PARENT, CODE_CLASSIF, REF_TYPE, REF_REGISTRATURA, REF_NAME, REF_LATIN, REF_GRJ, REF_INFO, DATE_OT, DATE_DO, TAX_OFFICE_NO, CONTACT_PHONE, CONTACT_EMAIL, MAX_UPLOAD_SIZE, EMPL_POSITION, EMPL_CONTRACT, NFL_EIK, FZL_EGN, FZL_LNC, FZL_LN_ES, FZL_BIRTH_DATE, USER_REG, DATE_REG, USER_LAST_MOD, DATE_LAST_MOD, LEVEL_NUMBER, MIG_LOGIN_NAME)
VALUES(25, 25, 23, 2, 24, 2, NULL, 'Даниела Димитрова', NULL, NULL, NULL, TO_DATE('1901-01-01','YYYY-MM-DD'), TO_DATE('2999-12-31','YYYY-MM-DD')
    , NULL, NULL, 'd.dimitrova@indexbg.bg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -1, TO_DATE('1901-01-01','YYYY-MM-DD'), NULL, NULL, NULL, NULL)
GO
INSERT INTO ADM_REFERENTS(REF_ID, CODE, CODE_PREV, CODE_PARENT, CODE_CLASSIF, REF_TYPE, REF_REGISTRATURA, REF_NAME, REF_LATIN, REF_GRJ, REF_INFO, DATE_OT, DATE_DO, TAX_OFFICE_NO, CONTACT_PHONE, CONTACT_EMAIL, MAX_UPLOAD_SIZE, EMPL_POSITION, EMPL_CONTRACT, NFL_EIK, FZL_EGN, FZL_LNC, FZL_LN_ES, FZL_BIRTH_DATE, USER_REG, DATE_REG, USER_LAST_MOD, DATE_LAST_MOD, LEVEL_NUMBER, MIG_LOGIN_NAME)
VALUES(24, 24, 25, 2, 24, 2, NULL, 'Десислава Харизанова', NULL, NULL, NULL, TO_DATE('1901-01-01','YYYY-MM-DD'), TO_DATE('2999-12-31','YYYY-MM-DD')
    , NULL, NULL, 'DKarapetrova@indexbg.bg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -1, TO_DATE('1901-01-01','YYYY-MM-DD'), NULL, NULL, NULL, NULL)
GO
INSERT INTO ADM_REFERENTS(REF_ID, CODE, CODE_PREV, CODE_PARENT, CODE_CLASSIF, REF_TYPE, REF_REGISTRATURA, REF_NAME, REF_LATIN, REF_GRJ, REF_INFO, DATE_OT, DATE_DO, TAX_OFFICE_NO, CONTACT_PHONE, CONTACT_EMAIL, MAX_UPLOAD_SIZE, EMPL_POSITION, EMPL_CONTRACT, NFL_EIK, FZL_EGN, FZL_LNC, FZL_LN_ES, FZL_BIRTH_DATE, USER_REG, DATE_REG, USER_LAST_MOD, DATE_LAST_MOD, LEVEL_NUMBER, MIG_LOGIN_NAME)
VALUES(30, 30, 24, 2, 24, 2, NULL, 'Ирена Динева', NULL, NULL, NULL, TO_DATE('1901-01-01','YYYY-MM-DD'), TO_DATE('2999-12-31','YYYY-MM-DD')
    , NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -1, TO_DATE('1901-01-01','YYYY-MM-DD'), NULL, NULL, NULL, NULL)
GO
INSERT INTO ADM_REFERENTS(REF_ID, CODE, CODE_PREV, CODE_PARENT, CODE_CLASSIF, REF_TYPE, REF_REGISTRATURA, REF_NAME, REF_LATIN, REF_GRJ, REF_INFO, DATE_OT, DATE_DO, TAX_OFFICE_NO, CONTACT_PHONE, CONTACT_EMAIL, MAX_UPLOAD_SIZE, EMPL_POSITION, EMPL_CONTRACT, NFL_EIK, FZL_EGN, FZL_LNC, FZL_LN_ES, FZL_BIRTH_DATE, USER_REG, DATE_REG, USER_LAST_MOD, DATE_LAST_MOD, LEVEL_NUMBER, MIG_LOGIN_NAME)
VALUES(33, 33, 30, 2, 24, 2, NULL, 'Марияна Алексиева', NULL, NULL, NULL, TO_DATE('1901-01-01','YYYY-MM-DD'), TO_DATE('2999-12-31','YYYY-MM-DD')
    , NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -1, TO_DATE('1901-01-01','YYYY-MM-DD'), NULL, NULL, NULL, NULL)
GO
INSERT INTO ADM_REFERENTS(REF_ID, CODE, CODE_PREV, CODE_PARENT, CODE_CLASSIF, REF_TYPE, REF_REGISTRATURA, REF_NAME, REF_LATIN, REF_GRJ, REF_INFO, DATE_OT, DATE_DO, TAX_OFFICE_NO, CONTACT_PHONE, CONTACT_EMAIL, MAX_UPLOAD_SIZE, EMPL_POSITION, EMPL_CONTRACT, NFL_EIK, FZL_EGN, FZL_LNC, FZL_LN_ES, FZL_BIRTH_DATE, USER_REG, DATE_REG, USER_LAST_MOD, DATE_LAST_MOD, LEVEL_NUMBER, MIG_LOGIN_NAME)
VALUES(35, 35, 33, 2, 24, 2, NULL, 'Николай Кънев', NULL, NULL, NULL, TO_DATE('1901-01-01','YYYY-MM-DD'), TO_DATE('2999-12-31','YYYY-MM-DD')
    , NULL, NULL, 'n.kanev@indexbg.bg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -1, TO_DATE('1901-01-01','YYYY-MM-DD'), NULL, NULL, NULL, NULL)
GO
 
DROP SEQUENCE SEQ_ADM_REFERENTS
GO
DROP SEQUENCE SEQ_ADM_REFERENTS_CODE
GO
CREATE SEQUENCE SEQ_ADM_REFERENTS INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 36 CACHE 1 NO CYCLE
GO
CREATE SEQUENCE SEQ_ADM_REFERENTS_CODE INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 START WITH 36 CACHE 1 NO CYCLE
GO


-- пассворд невер експире и други
update adm_users set pass_last_change = TO_DATE('2222-01-01','YYYY-MM-DD'), status_explain = null, status = 2, email = null, names = 'Системен служител' where user_id = -1
go


-- !!! СИСТЕМНИТЕ НАСТРОЙКИ !!!
update system_options set USER_REG = -1, DATE_REG = TO_DATE('01.01.1901','DD.MM.YYYY'), USER_LAST_MOD = null, DATE_LAST_MOD = null
go

-- всички се правят редактируеми от потребител
update SYSTEM_OPTIONS set USER_EDITABLE = 't'
go
-- тези долу стават забранени за промяна от потребител
update SYSTEM_OPTIONS set USER_EDITABLE = 'f' where OPTION_LABEL in ('system.classificationsForAccessControl','system.createUserFromAdmStruct','system.hiddenClassifications'
,'delo.classificationsForUserReplacement','system.classif.code.130','system.classif.code.110','system.classif.code.119','system.classif.code.145','system.classif.code.105'
,'system.showCompObjAudit','system.classif.code.22')
go

-- ЗАПИС НА ВЕРСИЯТА
delete from version_table -- TODO може да се дропне
go
insert into version_table(current_version, upgrade_time) 
values('1.01', current_timestamp)
go

-- Изтриване на всички тестове от логнати в мобилното
delete from mobile_logins -- TODO може да се дропне
go


WITH tbl AS
  (SELECT table_schema,
          TABLE_NAME
   FROM information_schema.tables
   WHERE TABLE_NAME not like 'pbc_%' and TABLE_NAME not like 'v_%' and TABLE_NAME not like 'ekatte_%' 
     AND table_schema in ('mms'))
SELECT table_schema,
       TABLE_NAME,
       (xpath('/row/c/text()', query_to_xml(format('select count(*) as c from %I.%I', table_schema, TABLE_NAME), FALSE, TRUE, '')))[1]::text::int AS rows_n
FROM tbl
ORDER BY rows_n DESC;