//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.13 at 10:15:39 AM EEST 
//


package com.ib.docu.utils;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ib.docu.utils package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Form1ZvlnZvlnDklrDLVhNomerDateDataNaPodavane_QNAME = new QName("", "date_dataNaPodavane");
    private final static QName _Form1ZvlnZvlnDklrDLVhNomerTxtVhodyashtNomer_QNAME = new QName("", "txt_vhodyashtNomer");
    private final static QName _Form1ZvlnZvlnDklrMainTxtEDeliverySource_QNAME = new QName("", "txtEDeliverySource");
    private final static QName _Form1ZvlnZvlnDklrMainTxtEDeliveryDestination_QNAME = new QName("", "txtEDeliveryDestination");
    private final static QName _Form1ZvlnZvlnDklrMainSportTurist_QNAME = new QName("", "sport_turist");
    private final static QName _Form1ZvlnZvlnDklrMainUniversitySport_QNAME = new QName("", "university_sport");
    private final static QName _Form1ZvlnZvlnDklrMainCboSettl_QNAME = new QName("", "cboSettl");
    private final static QName _Form1ZvlnZvlnDklrMainPredstavitelstvo_QNAME = new QName("", "predstavitelstvo");
    private final static QName _Form1ZvlnZvlnDklrMainAddrText_QNAME = new QName("", "addrText");
    private final static QName _Form1ZvlnZvlnDklrMainFormId_QNAME = new QName("", "formId");
    private final static QName _Form1ZvlnZvlnDklrMainWebPage_QNAME = new QName("", "webPage");
    private final static QName _Form1ZvlnZvlnDklrMainCboObl_QNAME = new QName("", "cboObl");
    private final static QName _Form1ZvlnZvlnDklrMainVid_QNAME = new QName("", "vid");
    private final static QName _Form1ZvlnZvlnDklrMainSignature_QNAME = new QName("", "signature");
    private final static QName _Form1ZvlnZvlnDklrMainCboObsht_QNAME = new QName("", "cboObsht");
    private final static QName _Form1ZvlnZvlnDklrMainContactPhone_QNAME = new QName("", "contactPhone");
    private final static QName _Form1ZvlnZvlnDklrMainNflEik_QNAME = new QName("", "nflEik");
    private final static QName _Form1ZvlnZvlnDklrMainUnitedSportClub_QNAME = new QName("", "united_sport_club");
    private final static QName _Form1ZvlnZvlnDklrMainContactEmail_QNAME = new QName("", "contactEmail");
    private final static QName _Form1ZvlnZvlnDklrMainGenSekDirektor_QNAME = new QName("", "genSekDirektor");
    private final static QName _Form1ZvlnZvlnDklrMainNachinPoluchavane_QNAME = new QName("", "nachinPoluchavane");
    private final static QName _Form1ZvlnZvlnDklrMainDatePodpisvane_QNAME = new QName("", "datePodpisvane");
    private final static QName _Form1ZvlnZvlnDklrMainPostCode_QNAME = new QName("", "postCode");
    private final static QName _Form1ZvlnZvlnDklrMainSportObedMf_QNAME = new QName("", "sportObedMf");
    private final static QName _Form1ZvlnZvlnDklrMainSportFederation_QNAME = new QName("", "sport_federation");
    private final static QName _Form1ZvlnZvlnDklrMainTxtSignatureYN_QNAME = new QName("", "txtSignatureYN");
    private final static QName _Form1ZvlnZvlnDklrMainVidSportList_QNAME = new QName("", "vidSportList");
    private final static QName _Form1ZvlnZvlnDklrMainAddressKoresp_QNAME = new QName("", "addressKoresp");
    private final static QName _Form1ZvlnZvlnDklrMainButton1_QNAME = new QName("", "Button1");
    private final static QName _Form1ZvlnZvlnDklrMainPredsedatel_QNAME = new QName("", "predsedatel");
    private final static QName _Form1ZvlnZvlnDklrMainStampIT_QNAME = new QName("", "StampIT");
    private final static QName _Form1ZvlnZvlnDklrMainUniversitySportText_QNAME = new QName("", "text");
    private final static QName _Form1ZvlnZvlnDklrMainUniversitySportCheckBox1_QNAME = new QName("", "CheckBox1");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ib.docu.utils
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Form1 }
     * 
     */
    public Form1 createForm1() {
        return new Form1();
    }

    /**
     * Create an instance of {@link Form1 .Zvln }
     * 
     */
    public Form1 .Zvln createForm1Zvln() {
        return new Form1 .Zvln();
    }

    /**
     * Create an instance of {@link Form1 .Zvln.ZvlnDklr }
     * 
     */
    public Form1 .Zvln.ZvlnDklr createForm1ZvlnZvlnDklr() {
        return new Form1 .Zvln.ZvlnDklr();
    }

    /**
     * Create an instance of {@link Form1 .Zvln.ZvlnDklr.Main }
     * 
     */
    public Form1 .Zvln.ZvlnDklr.Main createForm1ZvlnZvlnDklrMain() {
        return new Form1 .Zvln.ZvlnDklr.Main();
    }

    /**
     * Create an instance of {@link Form1 .Zvln.ZvlnDklr.DL }
     * 
     */
    public Form1 .Zvln.ZvlnDklr.DL createForm1ZvlnZvlnDklrDL() {
        return new Form1 .Zvln.ZvlnDklr.DL();
    }

    /**
     * Create an instance of {@link Form1 .MetadataFields }
     * 
     */
    public Form1 .MetadataFields createForm1MetadataFields() {
        return new Form1 .MetadataFields();
    }

    /**
     * Create an instance of {@link Form1 .DesignerStylesheet }
     * 
     */
    public Form1 .DesignerStylesheet createForm1DesignerStylesheet() {
        return new Form1 .DesignerStylesheet();
    }

    /**
     * Create an instance of {@link Form1 .Zvln.ZvlnDklr.Main.VidSportList }
     * 
     */
    public Form1 .Zvln.ZvlnDklr.Main.VidSportList createForm1ZvlnZvlnDklrMainVidSportList() {
        return new Form1 .Zvln.ZvlnDklr.Main.VidSportList();
    }

    /**
     * Create an instance of {@link Form1 .Zvln.ZvlnDklr.Main.SportObedMf }
     * 
     */
    public Form1 .Zvln.ZvlnDklr.Main.SportObedMf createForm1ZvlnZvlnDklrMainSportObedMf() {
        return new Form1 .Zvln.ZvlnDklr.Main.SportObedMf();
    }

    /**
     * Create an instance of {@link Form1 .Zvln.ZvlnDklr.Main.NachinPoluchavane }
     * 
     */
    public Form1 .Zvln.ZvlnDklr.Main.NachinPoluchavane createForm1ZvlnZvlnDklrMainNachinPoluchavane() {
        return new Form1 .Zvln.ZvlnDklr.Main.NachinPoluchavane();
    }

    /**
     * Create an instance of {@link Form1 .Zvln.ZvlnDklr.Main.SportFederation }
     * 
     */
    public Form1 .Zvln.ZvlnDklr.Main.SportFederation createForm1ZvlnZvlnDklrMainSportFederation() {
        return new Form1 .Zvln.ZvlnDklr.Main.SportFederation();
    }

    /**
     * Create an instance of {@link Form1 .Zvln.ZvlnDklr.Main.UnitedSportClub }
     * 
     */
    public Form1 .Zvln.ZvlnDklr.Main.UnitedSportClub createForm1ZvlnZvlnDklrMainUnitedSportClub() {
        return new Form1 .Zvln.ZvlnDklr.Main.UnitedSportClub();
    }

    /**
     * Create an instance of {@link Form1 .Zvln.ZvlnDklr.Main.SportTurist }
     * 
     */
    public Form1 .Zvln.ZvlnDklr.Main.SportTurist createForm1ZvlnZvlnDklrMainSportTurist() {
        return new Form1 .Zvln.ZvlnDklr.Main.SportTurist();
    }

    /**
     * Create an instance of {@link Form1 .Zvln.ZvlnDklr.Main.UniversitySport }
     * 
     */
    public Form1 .Zvln.ZvlnDklr.Main.UniversitySport createForm1ZvlnZvlnDklrMainUniversitySport() {
        return new Form1 .Zvln.ZvlnDklr.Main.UniversitySport();
    }

    /**
     * Create an instance of {@link Form1 .Zvln.ZvlnDklr.Main.StampIT }
     * 
     */
    public Form1 .Zvln.ZvlnDklr.Main.StampIT createForm1ZvlnZvlnDklrMainStampIT() {
        return new Form1 .Zvln.ZvlnDklr.Main.StampIT();
    }

    /**
     * Create an instance of {@link Form1 .Zvln.ZvlnDklr.DL.VhNomer }
     * 
     */
    public Form1 .Zvln.ZvlnDklr.DL.VhNomer createForm1ZvlnZvlnDklrDLVhNomer() {
        return new Form1 .Zvln.ZvlnDklr.DL.VhNomer();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date_dataNaPodavane", scope = Form1 .Zvln.ZvlnDklr.DL.VhNomer.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrDLVhNomerDateDataNaPodavane(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrDLVhNomerDateDataNaPodavane_QNAME, String.class, Form1 .Zvln.ZvlnDklr.DL.VhNomer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "txt_vhodyashtNomer", scope = Form1 .Zvln.ZvlnDklr.DL.VhNomer.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrDLVhNomerTxtVhodyashtNomer(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrDLVhNomerTxtVhodyashtNomer_QNAME, String.class, Form1 .Zvln.ZvlnDklr.DL.VhNomer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "txtEDeliverySource", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrMainTxtEDeliverySource(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrMainTxtEDeliverySource_QNAME, String.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "txtEDeliveryDestination", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<Integer> createForm1ZvlnZvlnDklrMainTxtEDeliveryDestination(Integer value) {
        return new JAXBElement<Integer>(_Form1ZvlnZvlnDklrMainTxtEDeliveryDestination_QNAME, Integer.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Form1 .Zvln.ZvlnDklr.Main.SportTurist }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sport_turist", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<Form1 .Zvln.ZvlnDklr.Main.SportTurist> createForm1ZvlnZvlnDklrMainSportTurist(Form1 .Zvln.ZvlnDklr.Main.SportTurist value) {
        return new JAXBElement<Form1 .Zvln.ZvlnDklr.Main.SportTurist>(_Form1ZvlnZvlnDklrMainSportTurist_QNAME, Form1 .Zvln.ZvlnDklr.Main.SportTurist.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Form1 .Zvln.ZvlnDklr.Main.UniversitySport }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "university_sport", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<Form1 .Zvln.ZvlnDklr.Main.UniversitySport> createForm1ZvlnZvlnDklrMainUniversitySport(Form1 .Zvln.ZvlnDklr.Main.UniversitySport value) {
        return new JAXBElement<Form1 .Zvln.ZvlnDklr.Main.UniversitySport>(_Form1ZvlnZvlnDklrMainUniversitySport_QNAME, Form1 .Zvln.ZvlnDklr.Main.UniversitySport.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cboSettl", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrMainCboSettl(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrMainCboSettl_QNAME, String.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "predstavitelstvo", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrMainPredstavitelstvo(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrMainPredstavitelstvo_QNAME, String.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addrText", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrMainAddrText(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrMainAddrText_QNAME, String.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "formId", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrMainFormId(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrMainFormId_QNAME, String.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "webPage", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrMainWebPage(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrMainWebPage_QNAME, String.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cboObl", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<Byte> createForm1ZvlnZvlnDklrMainCboObl(Byte value) {
        return new JAXBElement<Byte>(_Form1ZvlnZvlnDklrMainCboObl_QNAME, Byte.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vid", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrMainVid(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrMainVid_QNAME, String.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "signature", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrMainSignature(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrMainSignature_QNAME, String.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cboObsht", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrMainCboObsht(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrMainCboObsht_QNAME, String.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contactPhone", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<Integer> createForm1ZvlnZvlnDklrMainContactPhone(Integer value) {
        return new JAXBElement<Integer>(_Form1ZvlnZvlnDklrMainContactPhone_QNAME, Integer.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nflEik", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<Long> createForm1ZvlnZvlnDklrMainNflEik(Long value) {
        return new JAXBElement<Long>(_Form1ZvlnZvlnDklrMainNflEik_QNAME, Long.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Form1 .Zvln.ZvlnDklr.Main.UnitedSportClub }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "united_sport_club", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<Form1 .Zvln.ZvlnDklr.Main.UnitedSportClub> createForm1ZvlnZvlnDklrMainUnitedSportClub(Form1 .Zvln.ZvlnDklr.Main.UnitedSportClub value) {
        return new JAXBElement<Form1 .Zvln.ZvlnDklr.Main.UnitedSportClub>(_Form1ZvlnZvlnDklrMainUnitedSportClub_QNAME, Form1 .Zvln.ZvlnDklr.Main.UnitedSportClub.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contactEmail", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrMainContactEmail(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrMainContactEmail_QNAME, String.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "genSekDirektor", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrMainGenSekDirektor(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrMainGenSekDirektor_QNAME, String.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Form1 .Zvln.ZvlnDklr.Main.NachinPoluchavane }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nachinPoluchavane", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<Form1 .Zvln.ZvlnDklr.Main.NachinPoluchavane> createForm1ZvlnZvlnDklrMainNachinPoluchavane(Form1 .Zvln.ZvlnDklr.Main.NachinPoluchavane value) {
        return new JAXBElement<Form1 .Zvln.ZvlnDklr.Main.NachinPoluchavane>(_Form1ZvlnZvlnDklrMainNachinPoluchavane_QNAME, Form1 .Zvln.ZvlnDklr.Main.NachinPoluchavane.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datePodpisvane", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<XMLGregorianCalendar> createForm1ZvlnZvlnDklrMainDatePodpisvane(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Form1ZvlnZvlnDklrMainDatePodpisvane_QNAME, XMLGregorianCalendar.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "postCode", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<Short> createForm1ZvlnZvlnDklrMainPostCode(Short value) {
        return new JAXBElement<Short>(_Form1ZvlnZvlnDklrMainPostCode_QNAME, Short.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Form1 .Zvln.ZvlnDklr.Main.SportObedMf }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sportObedMf", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<Form1 .Zvln.ZvlnDklr.Main.SportObedMf> createForm1ZvlnZvlnDklrMainSportObedMf(Form1 .Zvln.ZvlnDklr.Main.SportObedMf value) {
        return new JAXBElement<Form1 .Zvln.ZvlnDklr.Main.SportObedMf>(_Form1ZvlnZvlnDklrMainSportObedMf_QNAME, Form1 .Zvln.ZvlnDklr.Main.SportObedMf.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Form1 .Zvln.ZvlnDklr.Main.SportFederation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sport_federation", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<Form1 .Zvln.ZvlnDklr.Main.SportFederation> createForm1ZvlnZvlnDklrMainSportFederation(Form1 .Zvln.ZvlnDklr.Main.SportFederation value) {
        return new JAXBElement<Form1 .Zvln.ZvlnDklr.Main.SportFederation>(_Form1ZvlnZvlnDklrMainSportFederation_QNAME, Form1 .Zvln.ZvlnDklr.Main.SportFederation.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "txtSignatureYN", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<Byte> createForm1ZvlnZvlnDklrMainTxtSignatureYN(Byte value) {
        return new JAXBElement<Byte>(_Form1ZvlnZvlnDklrMainTxtSignatureYN_QNAME, Byte.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Form1 .Zvln.ZvlnDklr.Main.VidSportList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vidSportList", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<Form1 .Zvln.ZvlnDklr.Main.VidSportList> createForm1ZvlnZvlnDklrMainVidSportList(Form1 .Zvln.ZvlnDklr.Main.VidSportList value) {
        return new JAXBElement<Form1 .Zvln.ZvlnDklr.Main.VidSportList>(_Form1ZvlnZvlnDklrMainVidSportList_QNAME, Form1 .Zvln.ZvlnDklr.Main.VidSportList.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addressKoresp", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrMainAddressKoresp(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrMainAddressKoresp_QNAME, String.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Button1", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrMainButton1(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrMainButton1_QNAME, String.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "predsedatel", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrMainPredsedatel(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrMainPredsedatel_QNAME, String.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Form1 .Zvln.ZvlnDklr.Main.StampIT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StampIT", scope = Form1 .Zvln.ZvlnDklr.Main.class)
    public JAXBElement<Form1 .Zvln.ZvlnDklr.Main.StampIT> createForm1ZvlnZvlnDklrMainStampIT(Form1 .Zvln.ZvlnDklr.Main.StampIT value) {
        return new JAXBElement<Form1 .Zvln.ZvlnDklr.Main.StampIT>(_Form1ZvlnZvlnDklrMainStampIT_QNAME, Form1 .Zvln.ZvlnDklr.Main.StampIT.class, Form1 .Zvln.ZvlnDklr.Main.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "text", scope = Form1 .Zvln.ZvlnDklr.Main.UniversitySport.class)
    public JAXBElement<String> createForm1ZvlnZvlnDklrMainUniversitySportText(String value) {
        return new JAXBElement<String>(_Form1ZvlnZvlnDklrMainUniversitySportText_QNAME, String.class, Form1 .Zvln.ZvlnDklr.Main.UniversitySport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CheckBox1", scope = Form1 .Zvln.ZvlnDklr.Main.UniversitySport.class)
    public JAXBElement<Byte> createForm1ZvlnZvlnDklrMainUniversitySportCheckBox1(Byte value) {
        return new JAXBElement<Byte>(_Form1ZvlnZvlnDklrMainUniversitySportCheckBox1_QNAME, Byte.class, Form1 .Zvln.ZvlnDklr.Main.UniversitySport.class, value);
    }

}
