//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.18 at 09:18:54 AM EEST 
//


package com.ib.mms.iscipr.client.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ib.iscipr.testClient.samlpe package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ib.iscipr.testClient.samlpe
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SportUnionsRequest }
     * 
     */
    public SportUnionsRequest createSportUnionsRequest() {
        return new SportUnionsRequest();
    }

    /**
     * Create an instance of {@link SportUnionsRequest.SportUnionsRecord }
     * 
     */
    public SportUnionsRequest.SportUnionsRecord createSportUnionsRequestSportUnionsRecord() {
        return new SportUnionsRequest.SportUnionsRecord();
    }

}
