//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.18 at 09:18:54 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://iscipr.egov.bg/SmartRegistry/SportUnionsRegisterRecordEntry", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ib.mms.iscipr.client.xsd;
