//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.18 at 09:18:54 AM EEST 
//


package com.ib.mms.iscipr.client.xsd;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SportUnionsRecord" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ExternalId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="SportUnionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SportUnionRegNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LicenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RegNumberEntryOrder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="EntryOrderDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="UnionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UnionLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UnionAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UnionStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UnionStatusDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="Sport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Presenter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AddressCorespondant" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Emails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="EIK" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="WebPage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ForeignData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CancelationOrder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CancelDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sportUnionsRecord"
})
@XmlRootElement(name = "SportUnionsRequest")
public class SportUnionsRequest {

    @XmlElement(name = "SportUnionsRecord", required = true)
    protected List<SportUnionsRequest.SportUnionsRecord> sportUnionsRecord;

    /**
     * Gets the value of the sportUnionsRecord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sportUnionsRecord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSportUnionsRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SportUnionsRequest.SportUnionsRecord }
     * 
     * 
     */
    public List<SportUnionsRequest.SportUnionsRecord> getSportUnionsRecord() {
        if (sportUnionsRecord == null) {
            sportUnionsRecord = new ArrayList<SportUnionsRequest.SportUnionsRecord>();
        }
        return this.sportUnionsRecord;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ExternalId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="SportUnionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SportUnionRegNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LicenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RegNumberEntryOrder" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="EntryOrderDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="UnionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UnionLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UnionAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UnionStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UnionStatusDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="Sport" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Presenter" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AddressCorespondant" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Emails" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="EIK" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="WebPage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ForeignData" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CancelationOrder" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CancelDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "externalId",
        "sportUnionType",
        "sportUnionRegNumber",
        "licenceNumber",
        "regNumberEntryOrder",
        "entryOrderDate",
        "unionName",
        "unionLocation",
        "unionAddress",
        "unionStatus",
        "unionStatusDate",
        "sport",
        "presenter",
        "addressCorespondant",
        "telephone",
        "emails",
        "eik",
        "webPage",
        "foreignData",
        "cancelationOrder",
        "cancelDate"
    })
    public static class SportUnionsRecord {

        public SportUnionsRecord( ) {
			super();			 
		}

		@XmlElement(name = "ExternalId")
        protected String externalId;
        @XmlElement(name = "SportUnionType", required = true)
        protected String sportUnionType;
        @XmlElement(name = "SportUnionRegNumber", required = true)
        protected String sportUnionRegNumber;
        @XmlElement(name = "LicenceNumber", required = true)
        protected String licenceNumber;
        @XmlElement(name = "RegNumberEntryOrder", required = true)
        protected String regNumberEntryOrder;
        @XmlElement(name = "EntryOrderDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar entryOrderDate;
        @XmlElement(name = "UnionName", required = true)
        protected String unionName;
        @XmlElement(name = "UnionLocation", required = true)
        protected String unionLocation;
        @XmlElement(name = "UnionAddress", required = true)
        protected String unionAddress;
        @XmlElement(name = "UnionStatus", required = true)
        protected String unionStatus;
        @XmlElement(name = "UnionStatusDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar unionStatusDate;
        @XmlElement(name = "Sport", required = true)
        protected String sport;
        @XmlElement(name = "Presenter", required = true)
        protected String presenter;
        @XmlElement(name = "AddressCorespondant", required = true)
        protected String addressCorespondant;
        @XmlElement(name = "Telephone", required = true)
        protected String telephone;
        @XmlElement(name = "Emails", required = true)
        protected String emails;
        @XmlElement(name = "EIK", required = true)
        protected BigInteger eik;
        @XmlElement(name = "WebPage", required = true)
        protected String webPage;
        @XmlElement(name = "ForeignData", required = true)
        protected String foreignData;
        @XmlElement(name = "CancelationOrder", required = true)
        protected String cancelationOrder;
        @XmlElement(name = "CancelDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar cancelDate;

        /**
         * Gets the value of the externalId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExternalId() {
            return externalId;
        }

        /**
         * Sets the value of the externalId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExternalId(String value) {
            this.externalId = value;
        }

        /**
         * Gets the value of the sportUnionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSportUnionType() {
            return sportUnionType;
        }

        /**
         * Sets the value of the sportUnionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSportUnionType(String value) {
            this.sportUnionType = value;
        }

        /**
         * Gets the value of the sportUnionRegNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSportUnionRegNumber() {
            return sportUnionRegNumber;
        }

        /**
         * Sets the value of the sportUnionRegNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSportUnionRegNumber(String value) {
            this.sportUnionRegNumber = value;
        }

        /**
         * Gets the value of the licenceNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLicenceNumber() {
            return licenceNumber;
        }

        /**
         * Sets the value of the licenceNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLicenceNumber(String value) {
            this.licenceNumber = value;
        }

        /**
         * Gets the value of the regNumberEntryOrder property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegNumberEntryOrder() {
            return regNumberEntryOrder;
        }

        /**
         * Sets the value of the regNumberEntryOrder property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegNumberEntryOrder(String value) {
            this.regNumberEntryOrder = value;
        }

        /**
         * Gets the value of the entryOrderDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEntryOrderDate() {
            return entryOrderDate;
        }

        /**
         * Sets the value of the entryOrderDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEntryOrderDate(XMLGregorianCalendar value) {
            this.entryOrderDate = value;
        }

        /**
         * Gets the value of the unionName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnionName() {
            return unionName;
        }

        /**
         * Sets the value of the unionName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnionName(String value) {
            this.unionName = value;
        }

        /**
         * Gets the value of the unionLocation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnionLocation() {
            return unionLocation;
        }

        /**
         * Sets the value of the unionLocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnionLocation(String value) {
            this.unionLocation = value;
        }

        /**
         * Gets the value of the unionAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnionAddress() {
            return unionAddress;
        }

        /**
         * Sets the value of the unionAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnionAddress(String value) {
            this.unionAddress = value;
        }

        /**
         * Gets the value of the unionStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnionStatus() {
            return unionStatus;
        }

        /**
         * Sets the value of the unionStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnionStatus(String value) {
            this.unionStatus = value;
        }

        /**
         * Gets the value of the unionStatusDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getUnionStatusDate() {
            return unionStatusDate;
        }

        /**
         * Sets the value of the unionStatusDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setUnionStatusDate(XMLGregorianCalendar value) {
            this.unionStatusDate = value;
        }

        /**
         * Gets the value of the sport property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSport() {
            return sport;
        }

        /**
         * Sets the value of the sport property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSport(String value) {
            this.sport = value;
        }

        /**
         * Gets the value of the presenter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPresenter() {
            return presenter;
        }

        /**
         * Sets the value of the presenter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPresenter(String value) {
            this.presenter = value;
        }

        /**
         * Gets the value of the addressCorespondant property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddressCorespondant() {
            return addressCorespondant;
        }

        /**
         * Sets the value of the addressCorespondant property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddressCorespondant(String value) {
            this.addressCorespondant = value;
        }

        /**
         * Gets the value of the telephone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelephone() {
            return telephone;
        }

        /**
         * Sets the value of the telephone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTelephone(String value) {
            this.telephone = value;
        }

        /**
         * Gets the value of the emails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmails() {
            return emails;
        }

        /**
         * Sets the value of the emails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmails(String value) {
            this.emails = value;
        }

        /**
         * Gets the value of the eik property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getEIK() {
            return eik;
        }

        /**
         * Sets the value of the eik property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setEIK(BigInteger value) {
            this.eik = value;
        }

        /**
         * Gets the value of the webPage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWebPage() {
            return webPage;
        }

        /**
         * Sets the value of the webPage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWebPage(String value) {
            this.webPage = value;
        }

        /**
         * Gets the value of the foreignData property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getForeignData() {
            return foreignData;
        }

        /**
         * Sets the value of the foreignData property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setForeignData(String value) {
            this.foreignData = value;
        }

        /**
         * Gets the value of the cancelationOrder property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCancelationOrder() {
            return cancelationOrder;
        }

        /**
         * Sets the value of the cancelationOrder property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCancelationOrder(String value) {
            this.cancelationOrder = value;
        }

        /**
         * Gets the value of the cancelDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCancelDate() {
            return cancelDate;
        }

        /**
         * Sets the value of the cancelDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCancelDate(XMLGregorianCalendar value) {
            this.cancelDate = value;
        }

    }

}
