package com.ib.mms.iscipr.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2022-10-19T16:06:20.257+03:00
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "RegisterManagementService",
                  wsdlLocation = "http://corporate.orak365.net/SmartRegistryAPI/RegisterManagementService.svc?singleWsdl",
                  targetNamespace = "http://iscipr.egov.bg/")
public class RegisterManagementService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://iscipr.egov.bg/", "RegisterManagementService");
    public final static QName BasicHttpBindingIRegisterManagementService = new QName("http://iscipr.egov.bg/", "BasicHttpBinding_IRegisterManagementService");
    static {
        URL url = null;
        try {
            url = new URL("http://corporate.orak365.net/SmartRegistryAPI/RegisterManagementService.svc?singleWsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegisterManagementService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://corporate.orak365.net/SmartRegistryAPI/RegisterManagementService.svc?singleWsdl");
        }
        WSDL_LOCATION = url;
    }

    public RegisterManagementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegisterManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegisterManagementService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RegisterManagementService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RegisterManagementService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RegisterManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IRegisterManagementService
     */
    @WebEndpoint(name = "BasicHttpBinding_IRegisterManagementService")
    public IRegisterManagementService getBasicHttpBindingIRegisterManagementService() {
        return super.getPort(BasicHttpBindingIRegisterManagementService, IRegisterManagementService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRegisterManagementService
     */
    @WebEndpoint(name = "BasicHttpBinding_IRegisterManagementService")
    public IRegisterManagementService getBasicHttpBindingIRegisterManagementService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIRegisterManagementService, IRegisterManagementService.class, features);
    }

}
