call sass --update . --no-source-map
rmdir "META-INF" /s /q
mkdir "META-INF\resources"
Xcopy /E /I "primefaces-mirage-index-blue-dark\*.css" "META-INF\resources\primefaces-mirage-index-blue-dark"
Xcopy /E /I "primefaces-mirage-index-blue-light\*.css" "META-INF\resources\primefaces-mirage-index-blue-light"
Xcopy /E /I "primefaces-mirage-index-brown-dark\*.css" "META-INF\resources\primefaces-mirage-index-brown-dark"
Xcopy /E /I "primefaces-mirage-index-brown-light\*.css" "META-INF\resources\primefaces-mirage-index-brown-light"
Xcopy /E /I "primefaces-mirage-index-cyan-dark\*.css" "META-INF\resources\primefaces-mirage-index-cyan-dark"
Xcopy /E /I "primefaces-mirage-index-cyan-light\*.css" "META-INF\resources\primefaces-mirage-index-cyan-light"
Xcopy /E /I "primefaces-mirage-index-green-dark\*.css" "META-INF\resources\primefaces-mirage-index-green-dark"
Xcopy /E /I "primefaces-mirage-index-green-light\*.css" "META-INF\resources\primefaces-mirage-index-green-light"
Xcopy /E /I "primefaces-mirage-index-indigo-dark\*.css" "META-INF\resources\primefaces-mirage-index-indigo-dark"
Xcopy /E /I "primefaces-mirage-index-indigo-light\*.css" "META-INF\resources\primefaces-mirage-index-indigo-light"
Xcopy /E /I "primefaces-mirage-index-lime-dark\*.css" "META-INF\resources\primefaces-mirage-index-lime-dark"
Xcopy /E /I "primefaces-mirage-index-lime-light\*.css" "META-INF\resources\primefaces-mirage-index-lime-light"
Xcopy /E /I "primefaces-mirage-index-magenta-dark\*.css" "META-INF\resources\primefaces-mirage-index-magenta-dark"
Xcopy /E /I "primefaces-mirage-index-magenta-light\*.css" "META-INF\resources\primefaces-mirage-index-magenta-light"
Xcopy /E /I "primefaces-mirage-index-orange-dark\*.css" "META-INF\resources\primefaces-mirage-index-orange-dark"
Xcopy /E /I "primefaces-mirage-index-orange-light\*.css" "META-INF\resources\primefaces-mirage-index-orange-light"
Xcopy /E /I "primefaces-mirage-index-purple-dark\*.css" "META-INF\resources\primefaces-mirage-index-purple-dark"
Xcopy /E /I "primefaces-mirage-index-purple-light\*.css" "META-INF\resources\primefaces-mirage-index-purple-light"
Xcopy /E /I "primefaces-mirage-index-red-dark\*.css" "META-INF\resources\primefaces-mirage-index-red-dark"
Xcopy /E /I "primefaces-mirage-index-red-light\*.css" "META-INF\resources\primefaces-mirage-index-red-light"
Xcopy /E /I "primefaces-mirage-index-teal-dark\*.css" "META-INF\resources\primefaces-mirage-index-teal-dark"
Xcopy /E /I "primefaces-mirage-index-teal-light\*.css" "META-INF\resources\primefaces-mirage-index-teal-light"
Xcopy /E /I "primefaces-mirage-index-yellow-dark\*.css" "META-INF\resources\primefaces-mirage-index-yellow-dark"
Xcopy /E /I "primefaces-mirage-index-yellow-light\*.css" "META-INF\resources\primefaces-mirage-index-yellow-light"
jar cf index-themes.jar META-INF
rmdir "META-INF" /s /q